spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=truw&useSSL=false
    username: root
    password: 357315807  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
